name: flutter_app

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # ui
  gap: ^3.0.1
  wolt_responsive_layout_grid: ^0.0.3
  drop_zone: ^1.0.2
  file_picker: ^5.3.3

  # utils
  go_router: ^9.0.3
  easy_localization: ^3.0.2
  path_provider: ^2.0.15
  logger: ^2.0.1

  # firebase
  firebase_core: ^2.15.0
  firebase_core_web: ^2.6.0
  firebase_auth: ^4.7.0
  firebase_auth_web: ^5.6.0
  firebase_dynamic_links: ^5.3.4

  # state management
  flutter_bloc: ^8.1.3
  hydrated_bloc: ^9.1.2

  # code generation
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  # lint
  flutter_lints: ^2.0.0

  # code generation
  build_runner: ^2.4.6
  freezed: ^2.3.5
  json_serializable: ^6.7.1

flutter:

  uses-material-design: true

  assets:
    - assets/translations/
